name: CI

on: [push]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Install pipenv
        run: pip install pipenv

      - name: Setup Python
        uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
        with:
          python-version: "3.10"
          cache: "pipenv"

      - name: Install packages
        run: pipenv install --dev

      - name: Lint
        run: pipenv run lint

      - name: Pytest
        run: pipenv run pytest
