name: CI

on: [push]

permissions:
  contents: read

jobs:
  ci:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install pipenv
        run: pip install pipenv

      - name: Setup Python
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
        with:
          python-version: "3.14"
          cache: "pipenv"

      - name: Install packages
        run: pipenv install --dev

      - name: Lint
        run: pipenv run lint

      - name: Pytest
        run: pipenv run pytest
